### ISSUE TITLE
“跳转(新版本app)”失败

### ISSUE THREAD

**Issue by zhongfly** [savvym/dmzjSearch#1]
动漫之家社区版：版本:1.0.005
Android 10
尝试多个漫画均无法使用“跳转新版本app“在动漫之家社区版打开漫画，”跳转旧版本app“能正常在动漫之家(非社区版)打开漫画。

**Comment by savvym** [comment]
跳转新版本那个是为了解决ios端的旧版“互享版”和新版"动漫之家Pro"接口改变的问题。
不过目前ios的旧版本“互享版”升级ios14之后会闪退无法使用，所以跳新版本可以看成是ios用的。
动漫之家社区版目前还没有能用的app内的url规则，所以并无法对于社区版使用。

**Comment by zhongfly** [comment]
> 跳转新版本那个是为了解决ios端的旧版“互享版”和新版"动漫之家Pro"接口改变的问题。
> 不过目前ios的旧版本“互享版”升级ios14之后会闪退无法使用，所以跳新版本可以看成是ios用的。
> 动漫之家社区版目前还没有能用的app内的url规则，所以并无法对于社区版使用。

谢谢解答
